<?php

namespace Vanengers\Copy\Tests\Excludes;

use PHPUnit\Framework\TestCase;
use PHPUnit\Util\Filesystem;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Vanengers\Copy\Command\CopyCommand;

class FoldersTest extends TestCase
{
    public $root;
    public $destination;
    public $source;

    public function setUp(): void
    {
        $this->source = 'C:\_GIT\copy';
        $this->root = 'C:\_GIT\copy\tests\copy_test';
        $this->destination = $this->root . '\destination';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testCanCopyFolderExists()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }

    public function testCanCopyFolderExistsAndGitHubFolderNonExisting()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $this->assertDirectoryDoesNotExist($this->destination.'\.github');
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }

    public function testCanCopyFolderExistsAndGitHubFolderExisting()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
                '--ignoreDotFiles' => false
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $this->assertDirectoryExists($this->destination.'\.github');
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }

    public function testCanCopyFolderExistsAndComposerFilesNonExisting()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $this->assertFileDoesNotExist($this->destination.'\composer.lock');
        $this->assertFileDoesNotExist($this->destination.'\composer.json');
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }

    public function testCanCopyFolderExistsAndComposerFilesExisting()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
                '--ignoreComposer' => false
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $this->assertFileExists($this->destination.'\composer.lock');
        $this->assertFileExists($this->destination.'\composer.json');
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }

    public function testCanCopyFolderExistsAndDotFileExists()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
                '--ignoreDotFiles' => false
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $this->assertFileExists($this->destination.'\.phpunit.result.cache');
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }

    public function testCanCopyFolderExistsAndDotFileNotExists()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
                '--ignoreDotFiles' => true
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $this->assertFileDoesNotExist($this->destination.'\.phpunit.result.cache');
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }

    public function testCanCopyFolderExistsAndGitFolderNotExists()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
                '--ignoreVCS' => true
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $this->assertDirectoryDoesNotExist($this->destination.'\.git');
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }

    public function testCanCopyFolderExistsAndGitFolderExists()
    {
        $copy = new CopyCommand();
        $copy->run(
            new ArrayInput([
                '--source' => 'C:\_GIT\copy',
                '--destination' => $this->destination,
                '--ignoreVCS' => false,
                '--ignoreDotFiles' => false, // .git is vcs ans also a dot folder
            ]),
            new ConsoleOutput()
        );
        $this->assertDirectoryExists($this->destination);
        $this->assertDirectoryExists($this->destination.'\.git');
        $fs = new \Symfony\Component\Filesystem\Filesystem();
        $fs->remove($this->root);
    }
}
